name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} ghcr.io
          DOCKER_BUILDKIT=1 docker build -t ghcr.io/${{github.repository}}:latest .
          docker push ghcr.io/${{github.repository}}:latest